### ISSUE TITLE
Running from command line with qgis_process, iface is None

### ISSUE THREAD

**Issue by velle** [enricofer/qgis_report_wizard#3]
I am hoping to be able to run the report generation from command line, without opening qgis. I assume this is supposed to be possible, am I right?

For the purpose of this issue report I used an entirely static HTML file, no_jinja.html; not a single bit of Jinja. I entered the details into the wizard and clicked Advanced -> Copy as qgis_process Command. 

The result, after inserting line breaks, is:

```
qgis_process run report_wizard:hypertext_report \
--distance_units=meters \
--area_units=m2 \
--ellipsoid=EPSG:7030 \
--TEMPLATE='/home/jdoe/myproj/report/html/no_jinja.html' \
--VECTOR_LAYER='/home/jdoe/myproj/lamps.shp' \
--LIMIT=100 \
--EMBED_IMAGES=false \
--OUTPUT='/home/jdoe/myproj/report/htmloutp/main.html'
```

For many templates, this does not work, because the templates often refer to a project. I recommend that the generated qgis_process command string also contains this parameter. I have added this line below. 

```
qgis_process run report_wizard:hypertext_report \
--distance_units=meters \
--area_units=m2 \
--ellipsoid=EPSG:7030 \
--TEMPLATE='/home/jdoe/myproj/report/html/no_jinja.html' \
--VECTOR_LAYER='/home/jdoe/myproj/lamps.shp' \
--LIMIT=100 \
--EMBED_IMAGES=false \
--OUTPUT='/home/jdoe/myproj/report/htmloutp/main.html' \
--project_path='/home/jdoe/myproj/søndergade.qgz'
```

However, this fails because iface is None. See the command line output below. 

```
/usr/lib/python3/dist-packages/qgis/utils.py:888: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  mod = _builtin_import(name, globals, locals, fromlist, level)
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Problem with SAGA installation: SAGA was not found or is not correctly installed

----------------
Inputs
----------------

EMBED_IMAGES:	false
LIMIT:	100
OUTPUT:	/home/jdoe/myproj/report/htmloutp/main.html
TEMPLATE:	/home/jdoe/myproj/report/html/no_jinja.html
VECTOR_LAYER:	/home/jdoe/myproj/lamps.shp

Using ellipsoid:	EPSG:7030
Using distance unit:	meters
Using area unit:	square meters

Logged critical: Traceback (most recent call last):
  File "/home/jdoe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_report_wizard/hypertext_report_alg.py", line 87, in processAlgorithm
    engine = hypertext_renderer(iface, vector_layer, feature_limit)
  File "/home/jdoe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_report_wizard/report_renderer.py", line 71, in __init__
    "image": "canvas:"+iface.mapCanvas().theme(),
AttributeError: 'NoneType' object has no attribute 'mapCanvas'

Traceback (most recent call last):
  File "/home/jdoe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_report_wizard/hypertext_report_alg.py", line 87, in processAlgorithm
    engine = hypertext_renderer(iface, vector_layer, feature_limit)
  File "/home/jdoe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_report_wizard/report_renderer.py", line 71, in __init__
    "image": "canvas:"+iface.mapCanvas().theme(),
AttributeError: 'NoneType' object has no attribute 'mapCanvas'

ERROR:	Traceback (most recent call last):
  File "/home/jdoe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_report_wizard/hypertext_report_alg.py", line 87, in processAlgorithm
    engine = hypertext_renderer(iface, vector_layer, feature_limit)
  File "/home/jdoe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_report_wizard/report_renderer.py", line 71, in __init__
    "image": "canvas:"+iface.mapCanvas().theme(),
AttributeError: 'NoneType' object has no attribute 'mapCanvas'

Traceback (most recent call last):
  File "/home/jdoe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_report_wizard/hypertext_report_alg.py", line 87, in processAlgorithm
    engine = hypertext_renderer(iface, vector_layer, feature_limit)
  File "/home/jdoe/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_report_wizard/report_renderer.py", line 71, in __init__
    "image": "canvas:"+iface.mapCanvas().theme(),
AttributeError: 'NoneType' object has no attribute 'mapCanvas'
```

Is this a bug? Am I using it wrong? Are my expectations of correct behavior wrong?

Is there some workaround to do the entire report generation from command line?

**Comment by enricofer** [comment]
Hi, unfortunately the current release of the plugin is not intended for command line processing, that is a use case that I never considered. But It would be interesting to investigate how to get rid of QgisInterface reference in command line processing. May be I could include the feature in a next release, but at the moment I'm working on other projects and I can currently assuring only bugfixing.
